language: php
php:
  - 5.5

before_install:
  - sudo apt-get install re2c libpcre3-dev

# TODO: fix the Zephir version via Composer
install:
  - cd /tmp
  - wget https://github.com/json-c/json-c/archive/0eedf3802fad2d41e45eecd92af529440f0d7d3a.zip -O json-c
  - unzip -q json-c
  - cd json-c-0eedf3802fad2d41e45eecd92af529440f0d7d3a
  - sh autogen.sh
  - ./configure
  - make
  - sudo make install
  - wget https://github.com/phalcon/zephir/archive/master.zip -O zephir
  - unzip -q zephir
  - cd zephir-master
  - sudo ./install -c
  - zephir
  - phpize -v

before_script:
  - cd $TRAVIS_BUILD_DIR && zephir build
  - composer install

# This hardcoded path is to change :/
script: php -dextension=symfony.so /home/travis/.phpenv/versions/5.5.9/bin/phpunit

#echo "extension=<extension>.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
