language: php
php:
  - 5.5

before_install:
  - sudo apt-get install re2c libpcre3-dev

# TODO: fix the Zephir version via Composer
install:
  - cd /tmp
  - wget https://github.com/json-c/json-c/archive/master.zip -O json-c
  - unzip -q json-c
  - cd json-c-master
  - sh autogen.sh
  - ./configure
  - make
  - sudo make install
  - wget https://github.com/phalcon/zephir/archive/master.zip -O zephir
  - unzip -q zephir
  - cd zephir-master
  - sudo ./install -c
  - zephir

before_script:
  - cd $TRAVIS_BUILD_DIR && zephir build
  - composer install

script: php -dextension=symfony.so /home/travis/.phpenv/shims/phpunit --debug tests/ContainerAwareEventDispatcherTest.php

#echo "extension=<extension>.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini